spring:
  application:
    name: resumeEvaluator-SpringAi-Workshop1

  ai:
    retry:
      max-attempts: 1

    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/

      chat:
        options:
          model: gpt-4o
          max-tokens: 1024
          temperature: 0.2

